add test section to the manifest

diff --git a/okteto.yml b/okteto.yml
--- a/okteto.yml
+++ b/okteto.yml
@@ -45,5 +45,23 @@ dev:
     sync:
       - e2e:/usr/src/app
 
-
-
+test:
+  e2e:
+    context: e2e
+    image: ${OKTETO_BUILD_E2E_IMAGE}
+    commands:
+      # OKTETO_DOMAIN is not properly propagated so hardcoding it here.
+      # See: https://github.com/okteto/okteto/pull/4324
+      #
+      # If test fails, we don't want to fail the pipeline so we exit with 0, otherwise
+      # the artifacts won't be synced.
+      - |
+        export MONGODB_PASSWORD=password
+        export MONGODB_USERNAME=okteto
+        export MONGODB_DATABASE=okteto
+        export MONGODB_HOST=mongodb
+        export OKTETO_DOMAIN=product.okteto.dev
+        yarn test || exit 0
+    artifacts:
+      - test-results
+      - playwright-report
